language: python

python:
  - "2.7"

env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.8

  
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libldap2-dev libsasl2-dev

 
install: 
 - pip install --verbose Django==$DJANGO_VERSION
 - pip install --verbose .
 - pip install --verbose -r testing-ci/requirements.txt 
 - pip install --verbose pep8 pyflakes

before_script:
 - pep8 --ignore=E501 django-auth-ldap-ad/
 - pyflakes django-auth-ldap-ad/
 
script: PYTHONPATH=$TRAVIS_BUILD_DIR python testing-ci/manage.py test django_auth_ldap_ad


