language: python

python:
  - "2.7"

env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.8

  
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libldap2-dev libsasl2-dev

 
install: 
 - pip install --verbose Django==$DJANGO_VERSION
 - pip install --verbose -r testing-ci/requirements.txt 

 
script: PYTHONPATH=$TRAVIS_BUILD_DIR python testing-ci/manage.py test django-auth-ldap-ad


